
ARG FROM_IMAGES
FROM $FROM_IMAGES

ARG PYTHONVERSION
ARG CONDAENV
ARG CUDAVERSION=cu118
ARG TARGETARCH

ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y
# 安装运维工具
RUN apt install -y -f --no-install-recommends vim apt-transport-https gnupg2 ca-certificates-java rsync jq  wget git dnsutils iputils-ping net-tools curl mysql-client locales zip unzip nginx lsof

# 安装中文
RUN apt install -y -f --no-install-recommends fontconfig locales ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy && locale-gen zh_CN && locale-gen zh_CN.utf8
ENV LANG=zh_CN.UTF-8
ENV LC_ALL=zh_CN.UTF-8
ENV LANGUAGE=zh_CN.UTF-8

# 便捷操作
RUN echo "alias ll='ls -alF'" >> ~/.bashrc && \
	echo "alias la='ls -A'" >> ~/.bashrc && \
	echo "alias vi='vim'" >> ~/.bashrc

# 安装amd64的conda
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh; \
    mkdir /root/.conda && bash Miniconda3-latest-Linux-x86_64.sh -b ; \
    rm -f Miniconda3-latest-Linux-x86_64.sh ; \
fi
# 安装arm64的conda
RUN if [ "$TARGETARCH" = "arm64" ]; then \
     wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-aarch64.sh ; \
    mkdir /root/.conda && bash Miniconda3-latest-Linux-aarch64.sh -b -u; \
    rm -f Miniconda3-latest-Linux-aarch64.sh ; \
fi

# 激活python3
ENV PATH=/root/miniconda3/bin:${PATH:-}
RUN conda create -y -n ${CONDAENV} python=${PYTHONVERSION}
ENV PATH=/root/miniconda3/envs/${CONDAENV}/bin:${PATH:-}
ENV CONDA_DEFAULT_ENV=${CONDAENV}


# 安装最新版的nodejs
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs && npm config set unicode false

# 安装启动sshd
RUN apt install -y openssh-server openssh-client

# 安装
RUN apt install -y -f python3-opencv ffmpeg
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip3 install celery==5.4.0 redis==5.2.0 pyarrow==18.0.0 requests-toolbelt==1.0.0 cryptography==43.0.3 tqdm==4.67.0 fsspec==2024.10.0 aiohttp==3.11.6 librosa==0.10.2.post1 flask==3.1.0 werkzeug==3.1.3 requests==2.32.3 tornado==6.2 Pillow==11.0.0 pysnooper==1.2.1 opencv-python==4.10.0.84 numpy==2.0.2 scipy==1.13.1 matplotlib==3.9.2 scikit-image==0.24.0 ipython==8.18.1 pyyaml==6.0.2 visualdl==2.5.3 filelock==3.16.1 && rm -rf ~/.cache

RUN pip install --upgrade "pip==24.3.1" && pip install tornado==6.2 gsutil==5.31 simplejson==3.19.3 sqlalchemy==2.0.36 joblib==1.4.2 scikit-learn==1.5.2 jinja2==3.1.4 requests==2.32.3 numpy==2.0.2 pandas==2.2.3 flask==3.1.0 pymysql==1.1.1 pysnooper==1.2.1 pyyaml==6.0.2 jupyterlab==3.6.3 voila==0.5.8 notebook==6.4.12 && rm -rf /tmp/* /var/tmp/* /root/.cache
RUN pip3 install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/${CUDAVERSION} && rm -rf /tmp/* /var/tmp/* /root/.cache
#RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
#RUN pip install --upgrade jupyterlab-git jupyterlab_tensorboard_pro && jupyter lab build && jupyter labextension install jupyterlab_tensorboard_pro && jupyter serverextension enable jupyterlab_tensorboard_pro --sys-prefix

# 环境变量
ENV NODE_HOME=/usr/local
ENV PATH=${PATH:-}:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV NODE_PATH=$NODE_HOME/lib/node_modules:${PATH:-}
ENV SHELL=/bin/bash

# 拷贝examples
COPY examples/* /examples/

# 环境初始化配置
COPY init.sh /init.sh

RUN echo "export PATH=/root/miniconda3/envs/python39/bin:/root/miniconda3/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> /etc/profile
