{
 "title": "node",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds{job=\"node-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "node pod cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", container=\"\",pod!=\"\",instance=~\"$node.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "node pod memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", container=\"\",pod!=\"\",instance=~\"$node.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "node pod GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod!='',instance=~\"$node.*\"}",
     "legendFormat": " {{instance}}，{{pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "node pod NPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_utilization{pod_name!='',instance=~\"$node.*\"}",
     "legendFormat": " {{instance}}，{{pod_name}} NPU {{id}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$node.*\"}[5m])) * 100)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=~\"$node.*\"} * 100",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=~\"$node.*\"} * 100",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=~\"$node.*\"} * 100",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n) * 100\n  /\nnode_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$node.*\"}\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=~\"$node.*\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=~\"$node.*\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{job=\"node-exporter\",  instance=~\"$node.*\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(node_filesystem_size_bytes{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$node.*\"})\n- sum(node_filesystem_avail_bytes{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$node.*\"})\n) * 100\n  /\nsum(node_filesystem_size_bytes{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$node.*\"})\n"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=~\"$node.*\", device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=~\"$node.*\", device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(device) (rate(node_infiniband_port_data_received_bytes_total{job=\"node-exporter\", instance=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(device) (rate(node_infiniband_port_data_transmitted_bytes_total{job=\"node-exporter\", instance=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}