"""empty message

Revision ID: 30f714129cdf
Revises: d327fd496e47
Create Date: 2022-08-02 07:38:39.893848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30f714129cdf'
down_revision = 'd327fd496e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('sqllchemy_uri', sa.String(length=255), nullable=True, comment='sql链接串'),
    sa.Column('table_name', sa.String(length=255), nullable=True, comment='表名'),
    sa.Column('label', sa.String(length=255), nullable=True, comment='中文名'),
    sa.Column('describe', sa.String(length=2000), nullable=True, comment='描述'),
    sa.Column('app', sa.String(length=255), nullable=True, comment='应用名'),
    sa.Column('owner', sa.String(length=2000), nullable=True, comment='责任人'),
    sa.Column('columns', sa.Text(), nullable=True, comment='列信息'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_table('metadata_table',
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('node_id', sa.String(length=200), nullable=True, comment='唯一性id'),
    sa.Column('app', sa.String(length=200), nullable=True, comment='所属应用'),
    sa.Column('c_org_fullname', sa.String(length=255), nullable=True, comment='所属组织架构'),
    sa.Column('db', sa.String(length=200), nullable=True, comment='库名'),
    sa.Column('table', sa.String(length=400), nullable=True, comment='表名'),
    sa.Column('metadata_column', sa.Text(), nullable=True, comment='列信息'),
    sa.Column('describe', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('owner', sa.String(length=200), nullable=True, comment='责任人'),
    sa.Column('lifecycle', sa.Integer(), nullable=True, comment='生命周期'),
    sa.Column('rec_lifecycle', sa.Integer(), nullable=True, comment='推荐生命周期'),
    sa.Column('storage_size', sa.String(length=200), nullable=True, comment='存储大小'),
    sa.Column('storage_cost', sa.Float(), nullable=True, comment='存储成本'),
    sa.Column('visits_seven', sa.Integer(), nullable=True, comment='7日访问量'),
    sa.Column('visits_thirty', sa.BigInteger(), nullable=True, comment='30日访问量'),
    sa.Column('visits_sixty', sa.BigInteger(), nullable=True, comment='60日访问量'),
    sa.Column('recent_visit', sa.Date(), nullable=True, comment='最新被访问时间'),
    sa.Column('partition_start', sa.String(length=255), nullable=True, comment='分区起点'),
    sa.Column('partition_end', sa.String(length=255), nullable=True, comment='分区终点'),
    sa.Column('status', sa.String(length=255), nullable=True, comment='状态'),
    sa.Column('creator', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('create_table_ddl', sa.Text(), nullable=True, comment='建表语句'),
    sa.Column('col_info', sa.Text(), nullable=True, comment='列信息'),
    sa.Column('partition_update_mode', sa.Integer(), nullable=True, comment='分区更新模式'),
    sa.Column('is_privilege', sa.Integer(), nullable=False, comment='是否特权'),
    sa.Column('data_source', sa.Integer(), nullable=True, comment='数据来源'),
    sa.Column('field', sa.String(length=200), nullable=True, comment='所属数据域'),
    sa.Column('security_level', sa.String(length=200), nullable=True, comment='安全等级'),
    sa.Column('value_score', sa.String(length=200), nullable=True, comment='价值评估'),
    sa.Column('warehouse_level', sa.String(length=200), nullable=True, comment='数仓级别'),
    sa.Column('ttl', sa.String(length=200), nullable=True, comment='保留时长'),
    sa.Column('expand', sa.Text(length=65536), nullable=True, comment='扩展参数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='英文名'),
    sa.Column('label', sa.String(length=200), nullable=True, comment='中文名'),
    sa.Column('describe', sa.String(length=2000), nullable=True, comment='描述'),
    sa.Column('source_type', sa.String(length=200), nullable=True, comment='数据集来源，开源，资产，采购'),
    sa.Column('source', sa.String(length=200), nullable=True, comment='数据集来源，github, 天池'),
    sa.Column('industry', sa.String(length=200), nullable=True, comment='行业'),
    sa.Column('icon', sa.String(length=2000), nullable=True, comment='数据集预览图片'),
    sa.Column('field', sa.String(length=200), nullable=True, comment='数据领域，视觉，听觉，文本'),
    sa.Column('usage', sa.String(length=200), nullable=True, comment='数据用途'),
    sa.Column('research', sa.String(length=200), nullable=True, comment='研究方向'),
    sa.Column('storage_class', sa.String(length=200), nullable=True, comment='存储类型，压缩'),
    sa.Column('file_type', sa.String(length=200), nullable=True, comment='文件类型，图片 png，音频'),
    sa.Column('status', sa.String(length=200), nullable=True, comment='文件类型  有待校验，已下线'),
    sa.Column('years', sa.String(length=200), nullable=True, comment='年份'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='关联url'),
    sa.Column('path', sa.String(length=400), nullable=True, comment='本地的持久化路径'),
    sa.Column('download_url', sa.String(length=1000), nullable=True, comment='下载地址'),
    sa.Column('storage_size', sa.String(length=200), nullable=True, comment='存储大小'),
    sa.Column('entries_num', sa.String(length=200), nullable=True, comment='记录数目'),
    sa.Column('duration', sa.String(length=200), nullable=True, comment='时长'),
    sa.Column('price', sa.String(length=200), nullable=True, comment='价格'),
    sa.Column('owner', sa.String(length=200), nullable=True, comment='责任人，*表示全部可见'),
    sa.Column('expand', sa.Text(length=65536), nullable=True, comment='扩展参数'),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_metric',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('app', sa.String(length=100), nullable=False, comment='应用名'),
    sa.Column('name', sa.String(length=300), nullable=True, comment='英文名'),
    sa.Column('label', sa.String(length=300), nullable=True, comment='中文名'),
    sa.Column('describe', sa.String(length=500), nullable=False, comment='描述'),
    sa.Column('caliber', sa.Text(length=65536), nullable=True, comment='数据负责人'),
    sa.Column('metric_type', sa.String(length=100), nullable=True, comment='指标类型  \t原子指标  衍生指标'),
    sa.Column('metric_level', sa.String(length=100), nullable=True, comment='指标等级   普通  重要  核心'),
    sa.Column('metric_dim', sa.String(length=100), nullable=True, comment='指标维度   天  月   周'),
    sa.Column('metric_data_type', sa.String(length=100), nullable=True, comment='指标类型  营收/规模/商业化'),
    sa.Column('metric_responsible', sa.String(length=200), nullable=True, comment='指标负责人'),
    sa.Column('status', sa.String(length=100), nullable=True, comment='状态  下线  上线   创建中'),
    sa.Column('task_id', sa.String(length=200), nullable=True, comment='所有相关任务id'),
    sa.Column('public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('expand', sa.Text(length=65536), nullable=True, comment='扩展参数'),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_pipeline',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='英文名'),
    sa.Column('describe', sa.String(length=200), nullable=False, comment='描述'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目组id'),
    sa.Column('dag_json', sa.Text(length=65536), nullable=True, comment='pipeline的上下游关系'),
    sa.Column('config', sa.Text(length=65536), nullable=True, comment='pipeline的全局配置'),
    sa.Column('expand', sa.Text(length=65536), nullable=True, comment='扩展参数'),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='英文名'),
    sa.Column('version', sa.String(length=100), nullable=True, comment='版本'),
    sa.Column('describe', sa.String(length=1000), nullable=True, comment='描述'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='模型路径'),
    sa.Column('download_url', sa.String(length=200), nullable=True, comment='下载url'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目组id'),
    sa.Column('pipeline_id', sa.Integer(), nullable=True, comment='任务流id'),
    sa.Column('run_id', sa.String(length=100), nullable=False, comment='run id'),
    sa.Column('run_time', sa.String(length=100), nullable=True, comment='运行时间'),
    sa.Column('framework', sa.String(length=100), nullable=True, comment='训练框架'),
    sa.Column('metrics', sa.Text(), nullable=True, comment='指标'),
    sa.Column('md5', sa.String(length=200), nullable=True, comment='md5值'),
    sa.Column('api_type', sa.String(length=100), nullable=True, comment='api类型'),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_task',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='英文名'),
    sa.Column('describe', sa.String(length=200), nullable=False, comment='描述'),
    sa.Column('etl_pipeline_id', sa.Integer(), nullable=False, comment='任务流id'),
    sa.Column('template', sa.String(length=100), nullable=False, comment='任务模板'),
    sa.Column('task_args', sa.Text(length=65536), nullable=True, comment='任务参数'),
    sa.Column('etl_task_id', sa.String(length=100), nullable=False, comment='远程调度系统任务id'),
    sa.Column('expand', sa.Text(length=65536), nullable=True, comment='扩展参数'),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['etl_pipeline_id'], ['etl_pipeline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('images', 'describe',
               existing_type=mysql.TEXT(),
               comment='描述',
               existing_comment='描述',
               nullable=False)
    op.add_column('inferenceservice', sa.Column('inference_config', sa.Text(length=65536), nullable=True, comment='配置文件'))
    op.add_column('inferenceservice', sa.Column('priority', sa.Integer(), nullable=True, comment='优先级'))
    op.alter_column('job_template', 'describe',
               existing_type=mysql.TEXT(),
               comment='描述',
               existing_comment='描述',
               nullable=False)
    op.add_column('nni', sa.Column('job_worker_command', sa.String(length=200), nullable=True, comment='执行命令'))
    op.add_column('nni', sa.Column('job_worker_image', sa.String(length=200), nullable=True, comment='执行镜像'))
    op.alter_column('nni', 'job_type',
               existing_type=mysql.ENUM('Job'),
               comment='任务类型',
               existing_comment='任务类型',
               nullable=True)
    op.alter_column('nni', 'namespace',
               existing_type=mysql.VARCHAR(length=200),
               comment='命名空间',
               existing_comment='命名空间',
               nullable=True)
    op.alter_column('project', 'describe',
               existing_type=mysql.TEXT(),
               comment='描述',
               existing_comment='描述',
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'describe',
               existing_type=mysql.TEXT(),
               comment='描述',
               existing_comment='描述',
               nullable=True)
    op.alter_column('nni', 'namespace',
               existing_type=mysql.VARCHAR(length=200),
               comment='命名空间',
               existing_comment='命名空间',
               nullable=False)
    op.alter_column('nni', 'job_type',
               existing_type=mysql.ENUM('Job'),
               comment='任务类型',
               existing_comment='任务类型',
               nullable=False)
    op.drop_column('nni', 'job_worker_image')
    op.drop_column('nni', 'job_worker_command')
    op.alter_column('job_template', 'describe',
               existing_type=mysql.TEXT(),
               comment='描述',
               existing_comment='描述',
               nullable=True)
    op.drop_column('inferenceservice', 'priority')
    op.drop_column('inferenceservice', 'inference_config')
    op.alter_column('images', 'describe',
               existing_type=mysql.TEXT(),
               comment='描述',
               existing_comment='描述',
               nullable=True)
    op.drop_table('etl_task')
    op.drop_table('model')
    op.drop_table('etl_pipeline')
    op.drop_table('metadata_metric')
    op.drop_table('dataset')
    op.drop_table('metadata_table')
    op.drop_table('dimension')
    # ### end Alembic commands ###
