"""empty message

Revision ID: 40e1215ccbd6
Revises: 593366be4eff
Create Date: 2026-05-27 10:55:28.077296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40e1215ccbd6'
down_revision = '593366be4eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('changed_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by_fk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('changed_by_fk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ab_user', ['changed_by_fk'], ['id'])
        batch_op.create_foreign_key(None, 'ab_user', ['created_by_fk'], ['id'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_type', sa.String(length=100), nullable=False, comment='镜像分类'))
        batch_op.add_column(sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'))
        batch_op.drop_constraint(batch_op.f('images_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('inferenceservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit', sa.String(length=100), nullable=True, comment='按IP限流 格式 N/second|N/minute|N/hour'))

    with op.batch_alter_table('metadata_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('changed_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by_fk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('changed_by_fk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ab_user', ['changed_by_fk'], ['id'])
        batch_op.create_foreign_key(None, 'ab_user', ['created_by_fk'], ['id'])

    with op.batch_alter_table('nni', schema=None) as batch_op:
        batch_op.alter_column('volume_mount',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_comment='挂载',
               existing_nullable=True)

    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.alter_column('volume_mount',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.String(length=2000),
               existing_comment='挂载',
               existing_nullable=True)

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'))

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'))

    with op.batch_alter_table('sqlab_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'))

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True, comment='项目组id'))
        batch_op.add_column(sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_column('expand')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('sqlab_query', schema=None) as batch_op:
        batch_op.drop_column('expand')

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_column('expand')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_column('expand')

    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.alter_column('volume_mount',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=400),
               existing_comment='挂载',
               existing_nullable=True)

    with op.batch_alter_table('nni', schema=None) as batch_op:
        batch_op.alter_column('volume_mount',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=100),
               existing_comment='挂载',
               existing_nullable=True)

    with op.batch_alter_table('metadata_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('changed_by_fk')
        batch_op.drop_column('created_by_fk')
        batch_op.drop_column('changed_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('inferenceservice', schema=None) as batch_op:
        batch_op.drop_column('rate_limit')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('images_ibfk_3'), 'project', ['project_id'], ['id'])
        batch_op.drop_column('expand')
        batch_op.drop_column('image_type')

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('changed_by_fk')
        batch_op.drop_column('created_by_fk')
        batch_op.drop_column('changed_on')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
