"""empty message

Revision ID: ba5f3a6868ac
Revises: 7f780f1c8d40
Create Date: 2022-09-30 07:47:42.904037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5f3a6868ac'
down_revision = '7f780f1c8d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aihub',
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('uuid', sa.String(length=2000), nullable=True, comment='当前版本的唯一主键'),
    sa.Column('status', sa.String(length=200), nullable=True, comment='状态'),
    sa.Column('doc', sa.String(length=200), nullable=True, comment='文档地址'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='英文名'),
    sa.Column('field', sa.String(length=200), nullable=True, comment='领域'),
    sa.Column('scenes', sa.String(length=200), nullable=True, comment='应用场景'),
    sa.Column('type', sa.String(length=200), nullable=True, comment='类型'),
    sa.Column('label', sa.String(length=200), nullable=True, comment='中文名'),
    sa.Column('describe', sa.String(length=2000), nullable=True, comment='描述'),
    sa.Column('source', sa.String(length=200), nullable=True, comment='来源'),
    sa.Column('pic', sa.String(length=500), nullable=True, comment='示例图片'),
    sa.Column('dataset', sa.Text(), nullable=True, comment='数据集的配置'),
    sa.Column('notebook', sa.String(length=2000), nullable=True, comment='notebook的配置'),
    sa.Column('job_template', sa.Text(), nullable=True, comment='任务模板参数'),
    sa.Column('pre_train_model', sa.String(length=2000), nullable=True, comment='预训练模型地址'),
    sa.Column('inference', sa.Text(), nullable=True, comment='推理服务的配置'),
    sa.Column('service', sa.Text(), nullable=True, comment='服务化参数'),
    sa.Column('version', sa.String(length=200), nullable=True, comment='版本'),
    sa.Column('hot', sa.Integer(), nullable=True, comment='热度'),
    sa.Column('price', sa.Integer(), nullable=True, comment='价格'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'dimension', ['sqllchemy_uri', 'table_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dimension', type_='unique')
    op.drop_table('aihub')
    # ### end Alembic commands ###
